name: cookietemple sync

on:
  schedule:
    - cron: '0 1 * * *' # 1 am UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Install cookietemple
          run: pip install cookietemple

        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
              token: '{% raw %}${{ secrets.CT_SYNC_TOKEN }}{% endraw %}'
          name: Check out source-code repository

        - uses: oleksiyrudenko/gha-git-credentials@v2
          with:
               name: 'cookiejar'
               email: 'philipp_ehm@protonmail.com'
               actor: 'Imipenem'
               token: '{% raw %}${{ secrets.CT_SYNC_TOKEN}}{% endraw %}'

        - name: Sync project
          run: cookietemple sync . {% raw %}${{ secrets.CT_SYNC_TOKEN  }}{% endraw %} Imipenem
